---
- name: Paush a script and run it
  hosts: localhost

  tasks:
          - script: /home/student/pyhello.py
            args:
                    executable: python3
            register: results
          
          - debug:
                  msg: "here is what came back: {{ results }}"

          - debug:
                  msg: " The output of the python is {{ results.stdout }}"



