---
- name: Play
  hosts: planet-express
  gather_facts: true

  tasks:
          - name: Reachout with get
            get_url:
                    url: https://www.random.org/integers/?num=1&min=0&max=1&col=1&base=10&format=plain&rnd=new
                    dest: ~/rand.txt
                    force: yes

          - name: read the rand.txt
            command: cat ~/rand.txt
            register: randvarz

          - name: "debug - Display a win"
            debug:
                    msg: "congratulations! {{ ansible_hostname }} won :)"
            when: randvarz.stdout =="1"

          - name: "debug - Display a failure"
            debug:
                    msg: "sorry! {{ ansible_hostname }} lost :("
            when: randvarz.stdout =="0"  
